services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: AXECOM_AI_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/galaxy_explorer.db:/app/galaxy_explorer.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=
    container_name: AXECOM_AI_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always