name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Rebuild & Restart Docker Containers
        run: |
          cd ~/galaxy-explorer
          docker compose up --build -d

      - name: Display Backend Logs
        run: |
          cd ~/galaxy-explorer
          sleep 3
          docker compose logs --tail=100 backend